apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gravitino-backend-ingress
  annotations:
    # Добавьте здесь необходимые аннотации для вашего Ingress контроллера
    # Например, если используете nginx-ingress:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: backend.devops-prod.gravitino.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gravitino-backend-service-dev
                port:
                  number: 80
