apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gravitino-backend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: backend.devops-prod.gravitino.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gravitino-backend-service-dev
                port:
                  number: 80
  tls:
  - hosts:
    - backend.devops-prod.gravitino.ru
    secretName: backend-prod-tls                  
