apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gravitino-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: frontend.devops-prod.gravitino.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gravitino-frontend-service-dev
                port:
                  number: 80
  tls:
    - hosts:
      - frontend.devops-prod.gravitino.ru
      secretName: frontend-prod-tls
