apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gravitino-frontend-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gravitino-frontend-service-dev
                port:
                  number: 3001
