apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gravitino-frontend-ingress
  annotations:
    # Добавьте здесь необходимые аннотации для вашего Ingress контроллера
    # Например, если используете nginx-ingress:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
    - host: frontend.gravitino.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gravitino-frontend-service-dev
                port:
                  name: https               
