apiVersion: v1
kind: Service
metadata:
  name: gravitino-frontend-service-dev
  labels:
    app: gravitino-frontend
spec:
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  type: ClusterIP    
  selector:
    app: gravitino-frontend
